name: json-bash
abstract: A JSON Loader/Dumper for Bash
version: 0.0.1
description: |
  This library provides functions to load JSON into an internal format, and to
  dump the internal format into JSON.
language: bash
keyword: [ bash, library, json, serialization, data ]
webpage: http://bpan.org/package/json
source: https://github.com/ingydotnet/json-bash.git
irc: irc.freenode.net/bpan
bugs: https://github.com/ingydotnet/json-bash/issues

author:
  name: Ingy döt Net
  email: ingy@ingy.net

license:
  type: MIT
  url: http://opensource.org/licenses/MIT

copyright:
  year: 2013

library:
- json.bash
test:
  run: make test

depend:
  os: posix
  language: bash >= 3.1
  test: prove
  make: gnu
